receivers:
  otlp:
    protocols:
      http: # <-- this is what enables POST to /v1/logs
        endpoint: "0.0.0.0:4318"

exporters:
  debug:
    verbosity: detailed

service:
  pipelines:
    logs:
      receivers: [otlp]
      exporters: [debug]
